name: Sweet Pumpkin Croquet

url: "http://localhost:4000"

baseurl: ""

description: Tech Blog description

author:
    name: Jason Dongkyu Kim
    email: jasonkim.softdev@gmail.com
    github: dongkyu9315
    linkedin: dongkyu9315
    bio: A Software Developer

highlighter: pygments

disqus: blog-jasondongkyukim

paginate: 4
paginate_path: "page:num"

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

timezone: Asia/Seoul

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
